---
:yaml:
  :datadir: "/opt/boxen/repo/config"
:hierarchy:
  - "people/%{::github_login}/nodes/%{::hostname}"
  - "people/%{::github_login}/nodes/%{::clientcert}"
  - "people/%{::github_login}/common"
  - "people/%{::github_login}"
  - "nodes/common"
  - "nodes/%{::clientcert}"
